### ISSUE TITLE
Provide a way to disambiguate filter sets with the same title

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/ezbeq#20]

**Comment by Mobe1969** [comment]
Is this to do with if there are several filters for a title, how to select? I was actually trying to figure how to do this. I know for several of mine I have both differing editions / cuts, as well as some others that are also in the BMiller repo. So if I'm wanting to use mine, I'd still nee to use the plugin.

**Comment by 3ll3d00d** [comment]
It is just about how to display this, I have the filters so they can be loaded but there seems to be no metadata that can be used to tell them apart (except the file name)

**Comment by 3ll3d00d** [comment]
edition and alt title now visible
