### ISSUE TITLE
Set volume to 100%

### ISSUE THREAD

**Issue by linerjoe** [3ll3d00d/ezbeq#34]
2 requests for this on AVS... when switching inputs/load title, set the master volume of the miniDSP to 100%.

**Comment by Mobe1969** [comment]
Thumbs up on that! Amount of times I've inadvertently touched either the mute or volume on the android app and stuffed it!

I wonder also on the output side, if it would be possible for it to load the house curve /compressor settings?

**Comment by 3ll3d00d** [comment]
I would not add a feature like that as an automatic, or even silent, option

it could only be added as either an explicit volume control or an option that comes with showing the current volume on screen

**Comment by Mobe1969** [comment]
Sure, that would be good. Even a separate SET button with a percentage?

**Comment by 3ll3d00d** [comment]
master volume can be set manually via the UI in 0.4.3
