### ISSUE TITLE
Set mDSP input gain

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/ezbeq#36]
I intend the "MV adjustments" published along with the BEQs to be applied as some combination of MV and mDSP input gain.  While R128 analysis does a pretty good job, it's far from perfect and so once a movie is started there is often an adjustment that needs to be made moving some of the "MV adjustment" between MV and mDSP input gain.  This allows the user to adjust MV to taste but still maintain the same bass level shown on the BEQ graph and designed around.

The current functionality of ezbeq and the inherent limitations of all mDSP apps to only function "one-way" means that if a BEQ is pushed via ezbeq and then one wants to make an adjustment as described above, they have to load up the mDSP app, which obviously forces a full load of the saved config, make the adjustment, and then re-push the filters via ezbeq.  Then if another further adjustment is needed (somewhat common occurrence) this process has to be repeated again.  This becomes extremely clunky to use and makes ezbeq arguably less convenient than just using the mDSP app and the merge method.

Adding the ability to set mDSP input gain from ezbeq would completely eliminate this problem.

**Comment by bozrdang** [comment]
I too would like to see this feature added.

**Comment by 3ll3d00d** [comment]
implemented in 0.4.3
