### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by matrox75** [3ll3d00d/ezbeq#43]
“Error” message when trying to load a movie to the pi while running minidsp-rs in servermode even after disconnecting minidsp HD plugin.

**Comment by 3ll3d00d** [comment]
pls share the ezbeq server process logs

**Comment by matrox75** [comment]
hello, will do it at the weekend. any tip for Command? guess journalctl is to much.

Gesendet von myMail für iOS

Sonntag, 18. April 2021, 20:43 +0200 von ***@***.*** ***@***.***>:

**Comment by matrox75** [comment]
Solved. Thanks to desertdog at avs.
