### ISSUE TITLE
Additional AVR/Pre-Pro Support

### ISSUE THREAD

**Issue by kernelpanic85** [3ll3d00d/ezbeq#55]
Any chance of adding support for processors other than the HTP-1 like the Anthem AVM 70?

**Comment by 3ll3d00d** [comment]
if the device has support for at least 9 custom filters (variable Q shelf filters & peaking eq) as well as an api that lets you set these then it can be done, if not it can't (anthem has neither unfortunately).

**Comment by kernelpanic85** [comment]
Thanks for the reply.  This might help my decision between Anthem and Monolith ;)
