### ISSUE TITLE
Collection tag search doesn't work if colon (:) in collection name

### ISSUE THREAD

**Issue by Mobe1969** [3ll3d00d/ezbeq#59]
The search feature doesn't seem to cover the collection tag if the tag text has a colon in it.

For example,  

<beq_collection id="115570">Star Trek: The Next Generation Collection</beq_collection>

Next Generation won't be found.

Same with
<beq_collection id="443996">Ghost in the Shell: Stand Alone Complex Collection</beq_collection>

**Comment by 3ll3d00d** [comment]
0.13.3 fixes this, really odd bug btw as it behaves like an else statement simply does not work. Javascript is a funny old language at times.
