### ISSUE TITLE
New Dependencies Added But Not Documented

### ISSUE THREAD

**Issue by tmowbrey** [3ll3d00d/ezbeq#60]
Hello,

I installed this application about a year ago and since then have completed standard upgrades. Today I deleted ezbeq and installed cleanly. While doing that, there were additional libraries that I had to install to install ezbeq:

libffi-dev
rustc
libssl-dev

It would be great if there was a portion of the documentation that itemized the dependencies to make it easier for new people to understand while libraries were required as well as providing notes for releases outlining what needed to be added to align with the newest version being installed.

**Comment by 3ll3d00d** [comment]
(known) dependencies are already specified

which OS is this on?

**Comment by tmowbrey** [comment]
Apologies for the delay in response.

I'm currently utilizing a Debian (Debian 10 - buster) container on a QNAP NAS.

**Comment by 3ll3d00d** [comment]
I don't think it is feasible for me to document how to build from source transitive dependencies. For example rust is a dependency of cryptography which this package does not directly depend on and you only require rust if you don't have a binary wheel available. Most platforms do but if yours doesn't then it's going to be with you to solve this.
