### ISSUE TITLE
Active Config preset doesn't refresh in EZBEQ UI

### ISSUE THREAD

**Issue by nicko88** [3ll3d00d/ezbeq#61]
Not a super huge issue, but I am finding that if the active config preset is changed outside of EZBEQ, like if it is changed via minidsp-rs API or via official minidsp app, when you refresh the EZBEQ interface, it doesn't show the correct active config preset.

It DOES show the correct master volume and master mute status though.  As far as I know, active preset is available from the minidsp-rs API just like master volume and master mute status.

After changing the config preset and master volume from the official minidsp app, I can refresh the EZBEQ interface and it does NOT match the preset that I can see is correctly listed in http://minidsp-rs:5380/devices/0/config.  But both EZBEQ and minidsp-rs API do correctly list the current master volume that was set in the official app.

**Comment by 3ll3d00d** [comment]
@nicko88 implemented in 0.15.0 , see the readme for info on how to configure (relies on minidsp rs websocket)
