### ISSUE TITLE
Feature request: Plex Webhook Integration

### ISSUE THREAD

**Issue by SteveDavis-TR** [3ll3d00d/ezbeq#62]
Having to manually switch profiles via smartphone isn't convenient - Adding adding support for plex webhooks would be a step to full automation (Hit play in plex, webhook called to update minidsp for selected movie) https://support.plex.tv/articles/115002267687-webhooks/

Webhooks sends a client uuid, so requested can be filtered to the specific relevant client.  I'm not entirely sure about determining the audio stream portion - would need to examine the metadata payload to see what's included there.

Other media server platforms(ex jellyfin) also have webhook support - payloads may be a little different, but should be easy enough to add api support for multiple media server apps as long as they provide a client id, movie title, and audio stream format.

**Comment by 3ll3d00d** [comment]
From the Plex example, it seems like it would need to filter on event (media.stop start) and Player.uuid (which you would add to ezbeq config) and then needs to be able to match something in the metadata with a beqcatalogue entry.  Not immediately obvious how to automatically do the last bit though there was a post on avs on this last point

**Comment by 3ll3d00d** [comment]
Plex docs are not too clear but it seems that it does have an option to include data from themoviedb (which is what beqcatalogue includes) which may make the lookup easier.

Details from an emby user on how they did it are in https://www.avsforum.com/threads/ezbeq-use-and-development-discussion.3181732/page-147#post-61848185 in case it helps

**Comment by iloveicedgreentea** [comment]
FYI this is on my roadmap to do. I am not sure if it will be part of this app or run as a separate daemon and talk to ezbeq via api. Probably won’t be any time soon, but I definitely plan on working on it in the next few weeks

**Comment by kanokkk** [comment]
Maybe it is possible with home assistant as an automated task? Does the ezbeq have an API?

**Comment by 3ll3d00d** [comment]
> Maybe it is possible with home assistant as an automated task? Does the ezbeq have an API?

yes, go to `/api/doc/` in a local installation for details

**Comment by ilanponmeta** [comment]
FYI almost done with this. Doing safety tests for BEQ and then I will release a preview version for testing

**Comment by iloveicedgreentea** [comment]
Almost done with this. Doing safety checks with beq and then I can release a preview version for testing.

**Comment by iloveicedgreentea** [comment]
Okay, a very alpha release is here https://github.com/iloveicedgreentea/plex-webhook-automation/tree/v0.0.4

Please read the readme as any question is likely answered there. I have tested all functions and it works, but YMMV so open issues if you find bugs. I plan on working on it more in the coming week and also adding IP based control for MadVR Envy too.

**Comment by kanokkk** [comment]
awesome job. Just trying to set it up - 
Step 0 - I made the config.json in HA with information from the config shown.
Step 1 - where should i make the pull? is it on my pi where HA is set up or the pi with ezbeq installed?

Can you perhaps make a short video setting the whole thing up? :-)

**Comment by iloveicedgreentea** [comment]
> where should i make the pull? is it on my pi where HA is set up or the pi with ezbeq installed?

It does not matter. Something that can run a container. If you are using HAOS on a pi I strongly recommend against doing anything on there, so use the one running ezbeq. I love HA but they are insane with their requirements for official add ons or integrations. 

A video wouldn’t be a good way to do this as it will take a lot of time and be outdated later on, so no real point. If anything in the readme is unclear please open an issue and I can clarify it.

You basically need MQTT set up on HA, webhooks setup on the plex server (port and IP pointing to where you set up this server) and thats pretty much it
