### ISSUE TITLE
Feature Idea: Integration with CamillaDSP

### ISSUE THREAD

**Issue by volschin** [3ll3d00d/ezbeq#66]
CamillaDSP is an open source software dsp allowing different filter pipelines. With an I/O card a raspberry pi can act as BEQ interface and dsp in one.
So it would be an interesting option to be able to choose this additional to MiniDSP and HTP-1.

what do you think?

**Comment by 3ll3d00d** [comment]
Sounds like a good idea, do you have an idea of how it would work? I suppose the user instructs where in the filter pipeline it should add the filters ?

**Comment by 3ll3d00d** [comment]
Probably need to use https://github.com/HEnquist/pycamilladsp

**Comment by volschin** [comment]
That’s right. A very good tutorial can be found at
https://www.audiosciencereview.com/forum/index.php?threads/rpi4-camilladsp-tutorial.29656/

**Comment by 3ll3d00d** [comment]
@volschin initial release in https://pypi.org/project/ezbeq/1.0.0b17/ 

Config instructions in https://github.com/3ll3d00d/ezbeq#camilladsp

**Comment by volschin** [comment]
Played around with it, works really fine, also from the concept how you have done it. Neither my mixers nor my other filters are impacted.
As the not implemented MV, it would probably best to use type „Gain“ for it.
I had an not easy reproducible problem probably from a restart of the camilla service, where the webservice of ezbeq not reconnected after camilla available again.

**Comment by 3ll3d00d** [comment]
https://github.com/3ll3d00d/ezbeq/releases/tag/1.0.0b19 adds support for gain/volume 

it also supports the live levels screen which uses the peak/rms values provided by camilladsp

![image](https://github.com/3ll3d00d/ezbeq/assets/2487509/d671b412-b90c-42dd-9dd3-6b57a2914f41)
