### ISSUE TITLE
Cannot install in python environment?

### ISSUE THREAD

**Issue by UncleBabyBilly** [3ll3d00d/ezbeq#70]
When attempting to install inside the python environment I get failures. I've attempted to upgrade pip, setuptools and wheel outside of the python environment to no avail.  What am I missing? I'd like to get it running in the python virtual environment.

Inside the python environment: 
`pip install ezbeq`

```
   × Running setup.py install for cffi did not run successfully.
        │ exit code: 1
        ╰─> [38 lines of output]
            running install
            /home/redacteduser/python/ezbeq/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```

Outside of the python environment runs fine: 
`python` -m pip install --upgrade ezbeq 

Environment: Orange Pi Zero on Armbian 23.02.2 Jammy with Linux 5.15.93-sunxi

**Comment by 3ll3d00d** [comment]
deprecation warning is just a warning so won't be the cause

you need to get the full output to see what actually fails, not sure if the above is trimmed for sharing or not

did you update various things outside before or after creating the venv?

**Comment by UncleBabyBilly** [comment]
> deprecation warning is just a warning so won't be the cause
> 
> you need to get the full output to see what actually fails, not sure if the above is trimmed for sharing or not
> 
> did you update various things outside before or after creating the venv?

Yes I installed various packages below outside of the python environment in an effort to get this running the latest error is  can't find Rust compiler.  

apt install python3 python3-venv python3-pip libyaml-dev
apt install libffi-dev
apt install python-dev-is-python3
apt install libbz2-dev liblzma-dev

Full log:   https://privatebin.net/?70fc19deb93cbae1#Civpmcc4cPPAJKrrbKbLkSR3RfVCzAr51y9wWnUezxJG

**Comment by 3ll3d00d** [comment]
your error comes from https://cryptography.io/en/40.0.2/installation/#rust  so you need to get rustc available to it

google suggested https://users.rust-lang.org/t/installing-rust-on-armbian/93694 so perhaps that is still accurate

**Comment by UncleBabyBilly** [comment]
> your error comes from https://cryptography.io/en/40.0.2/installation/#rust so you need to get rustc available to it
> 
> google suggested https://users.rust-lang.org/t/installing-rust-on-armbian/93694 so perhaps that is still accurate

For some reason when I attempt to install rust it fails on the rustc component.  gets killed during the install, dont know if that's a resource limitation on the Orange Pi Zero.

I am able to run ezbeq system level fine with no errors in the install , is there any real downside to running it that way if this device is dedicated to it?

**Comment by 3ll3d00d** [comment]
No, if it works then it's fine

**Comment by UncleBabyBilly** [comment]
> No, if it works then it's fine

The only issue I have running it this way is starting it as a service.  Any idea on how to address this?  ezbeq can start from the terminal otherwise just fine.

`ezbeq.service: Failed to locate executable /home/redacted/python/ezbeq/bin/ezbeq: No such file or directory`

```
[Unit]
Description=ezbeq
After=network.target

[Service]
Type=simple
User=redacted
WorkingDirectory=/home/redacted
ExecStart=/home/redacted/python/ezbeq/bin/ezbeq
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
```

**Comment by UncleBabyBilly** [comment]
I figured out the issue with the service. The path needed to be changed. Steps to remediate below. 

1) ran command `type ezbeq`
2) result was `ezbeq is hashed (/home/redacted/.local/bin/ezbeq)`
3) updated `/etc/systemd/system/ezbeq.service` to:
```
[Unit]
Description=ezbeq
After=network.target

[Service]
Type=simple
User=redacted
WorkingDirectory=/home/redacted
ExecStart=/home/redacted/.local/bin/ezbeq
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
```
