### ISSUE TITLE
QSC Qsys Support Using Biquads

### ISSUE THREAD

**Issue by rob-cohen** [3ll3d00d/ezbeq#71]
In order to remotely set biquads, a custom text control must be used as an intermediary, since Qsys doesn't support setting biquads directly. You only need one text field, but I am using 4 to display the current title and make the title and image paths available to be displayed in my Home Assistant dash. Feel free to change that as desired.

Steps:
1) Create "IIR Custom Filter" block. I renamed the block to "BEQ Filter". It's in my "Bass" section.
2) Select the block. Under properties, set the "Section Count" to 10 and check the "JSON" control pin.
3) Create a "Custom Controls" block. I renamed the block to "BEQ Text". It's in my "Control" section.
4) Select the block. Under properties, set Group 1 - Type to "Text edit", Group 1 - Count to "4", and Script Access - Script Access to "All".
5) You can set the text fields with a single call to the QRC API Component.Set for the custom control block. You can use Compontent.Get for clues on how to format it.
6) Route the Text 1 pin from the custom control block to the IIR block. This can use a label or a virtual wire.
7) Double-click the custom control block. I dragged the second field onto my workspace so I can view the current filter. (optional)
8) I also used a snapshot to make a button to clear BEQ. (optional) You can remotely set the text values to cleared mode, instead.
7) Emulate in Qsys Designer to test. When emulating, you can fill in the defaults to cleared mode, below. (Leave out the quotes.)

A couple example text fields.

Cleared mode:
1: "[1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0]"
2: ""
3: "https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/no-fun-no-bass.jpg"
4: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/A_black_image.jpg/1600px-A_black_image.jpg"

Fury filter loaded:
1: "[1.000101435924585,-1.9941925128076392,0.9941256744576228,1.0,-1.9941925128076392,0.9942271103822078,1.0003023658461123,-1.9976637381046947,0.9973683532294153,1.0,-1.9976650262427018,0.9976694309375205,1.0003023658461123,-1.9976637381046947,0.9973683532294153,1.0,-1.9976650262427018,0.9976694309375205,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0]"
2: "Fury (2014) BEQ Atmos"
3: "https://i.imgur.com/8Ic0pqO.jpg"
4: "https://i.imgur.com/wm8p70S.jpg"

My C# code for computing biquads for Qsys. Unused slots must have identity coefficients. The Qsys sample rate is 48000. 6 coefficients per Qsys biquad, so 60 total for 10 biquads.

```
public static void CalcIdentityBiquad(double[] vals, int pos)
{
	vals[pos + 0] = 1.0;
	vals[pos + 1] = 0.0;
	vals[pos + 2] = 0.0;
	vals[pos + 3] = 1.0;
	vals[pos + 4] = 0.0;
	vals[pos + 5] = 0.0;
}
```

```
public static void CalcPeakingBiquad(double[] vals, int pos,
	double freq, double q, double gain, double sampleRate)
{
	if (gain == 0.0)
	{
		CalcIdentityBiquad(vals, pos);
		return;
	}

	double A = Math.Pow(10.0, gain/40.0);
	double w0 = 2.0*Math.PI*freq/sampleRate;
	double alpha = Math.Sin(w0)/(2.0*q);
	double a0 = 1.0 + alpha/A;
	double inva0 = 1.0/a0;
	double cosw02 = 2.0*Math.Cos(w0);

	// b0
	vals[pos + 0] = (1.0 + alpha*A) * inva0;
	// b1
	vals[pos + 1] = -cosw02 * inva0;
	// b2
	vals[pos + 2] = (1.0 - alpha*A) * inva0;
	// a0
	vals[pos + 3] = 1.0;
	// a1
	vals[pos + 4] = -cosw02 * inva0;
	// a2
	vals[pos + 5] = (1.0 - alpha/A) * inva0;
}

```
```
public static void CalcLowShelfBiquad(double[] vals, int pos,
	double freq, double q, double gain, double sampleRate)
{
	if (gain == 0.0)
	{
		CalcIdentityBiquad(vals, pos);
		return;
	}

	double A = Math.Pow(10.0, gain/40.0);
	double sqrtA2 = 2.0*Math.Sqrt(A);
	double w0 = 2.0*Math.PI*freq/sampleRate;
	double cosw0 = Math.Cos(w0);
	double alpha = Math.Sin(w0)/(2.0*q);
	double a0 = (A + 1.0) + (A - 1.0)*cosw0 + sqrtA2*alpha;
	double inva0 = 1.0/a0;

	// b0
	vals[pos + 0] = (A*((A + 1.0) - (A - 1.0)*cosw0 + sqrtA2*alpha)) * inva0;
	// b1
	vals[pos + 1] = (2.0*A*((A - 1.0) - (A + 1.0)*cosw0)) * inva0;
	// b2
	vals[pos + 2] = (A*((A + 1.0) - (A - 1.0)*cosw0 - sqrtA2*alpha)) * inva0;
	// a0
	vals[pos + 3] = 1.0;
	// a1
	vals[pos + 4] = (-2.0*((A - 1.0) + (A + 1.0)*cosw0)) * inva0;
	// a2
	vals[pos + 5] = ((A + 1.0) + (A - 1.0)*cosw0 - sqrtA2*alpha) * inva0;
}
```

Design attached.
[qsys-core.zip](https://github.com/3ll3d00d/ezbeq/files/12793115/qsys-core.zip)

**Comment by 3ll3d00d** [comment]
I thought it was said that qsys use a different definition of q but those filter definitions look like standard ones at first glance? it means you're converting q as per https://www.andyc.diy-audio-engineering.org/parametric-eq-parameters/index.html before calling the code above? and converting q in that way is fine for shelf filters too?

**Comment by rob-cohen** [comment]
The Qsys PEQ block can use either a Hypex definition of Q or a different definition they call bandwidth. But, the PEQ block doesn't allow any Q parameter for low-shelf filters, so I used the biquad block instead of the PEQ block. That way I can create an accurate BEQ filter.

The code above generates Qsys biquad coefficients using the RBJ version of Q directly from the BEQ DB. So, Q should be used without any conversion.

**Comment by 3ll3d00d** [comment]
it seems a slightly circuitous route compared to the existing integration, I'd prefer to just drop an IIR component in place of the existing component and directly write to its coeffs control

e.g. if I send this to your project

    {'jsonrpc': '2.0', 'id': 1234, 'method': 'Component.Get', 'params': {'Name': 'BEQ_Filter', 'Controls': [{'Name': 'coeffs'}]}}

then I get

     {'jsonrpc': '2.0', 'result': {'Name': 'BEQ_Filter', 'Controls': [{'Name': 'coeffs', 'String': '1.00', 'Value': 1.0, 'Position': 0.50499999, 'Strings': ['1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0', '1.00', '0', '0'], 'Values': [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0], 'Positions': [0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5, 0.5049999952316284, 0.5, 0.5]}]}, 'id': 1234}

this back

**Comment by 3ll3d00d** [comment]
not sure what the rpc format for that is though, doesn't seem to match what is said in https://q-syshelp.qsc.com/Index.htm#Schematic_Library/filter_IIR.htm

**Comment by rob-cohen** [comment]
Indeed! That was my original strategy, but I couldn't find any way to write the array of coefficients, even after contacting Qsys support. It would only let me modify the first value. The only work-around we found was the Rube-Goldberg approach of setting a custom text control and indirectly feeding that to the IIR block. :(

**Comment by 3ll3d00d** [comment]
actually looking closer, I see the schematic shows that is the way

![image](https://github.com/3ll3d00d/ezbeq/assets/2487509/960c9e98-69e2-4ca3-8678-92f1f44112f5)

strange

your text control doesn't seem to be connected to the iir filter though?

**Comment by rob-cohen** [comment]
I'm using a label to do that, rather than a virtual wire. You can select a pin and type to give it a label. It's just a shortcut to manage clutter. No functional difference.

**Comment by rob-cohen** [comment]
https://youtu.be/L2vPaJrPTnI?si=2d_qjwq1aySEE2zS

**Comment by 3ll3d00d** [comment]
try 2.0.0a28 , readme updated with info on how to configure it 

appreciate if you can check the filters come through accurately

I hardcoded it to 48k fs atm as that is what the core110f uses, is that true for all qsys devices?

**Comment by rob-cohen** [comment]
I don't run ezBEQ, so I'm not set up to test it! Usually if something is wrong with the coefficients, the IIR block graph will be totally garbage. If it's not garbage, that's a good sign!

Yes, all Qsys models use 48khz, so that should be safe to hard code for the foreseeable future.
