### ISSUE TITLE
Blacklist specific Movies

### ISSUE THREAD

**Issue by Kekskruemel** [3ll3d00d/ezbeq#78]
Hi,

I am using Gowatchit for automatic filter settings. I have several movies already with a custom lfe track. Is there a way to set a blacklist of movies so ezbeq wouldn't apply the filters ?

Thx & Greetings

**Comment by 3ll3d00d** [comment]
Ezbeq only applies the filters you tell it to so isn't that a job for gowatchit?

**Comment by Kekskruemel** [comment]
Gowatchit developemwnt looks dead :/ could also protect you if you are only using ezbeq and movies with custom lfe track, but would understand if you dont want to add it.

**Comment by 3ll3d00d** [comment]
it really makes no sense to have a feature to suppress explicit API calls so closing this one, better to ask whoever develops the app you use to deal with it (and if that is a dead app then consider moving on)
